"""Geographic-name cleanup for Excel workbooks.

The cleaner treats the workbooks in ``Metadata`` as the canonical source. It
updates only recognized geographic columns in a copy of the input workbook and
writes a separate report for values that changed or need review.
"""

from __future__ import annotations

import re
import unicodedata
from collections import defaultdict
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter
from rapidfuzz import fuzz, process


ProgressCallback = Callable[[int, int, str], None]

REFERENCE_FILENAMES = {
    "region": "regions",
    "province": "provinces",
    "municipality": "municipalities",
}
PARENT_COLUMNS = {
    "region": None,
    "province": "region_id",
    "municipality": "province_id",
}
HEADER_ALIASES = {
    "region": "region",
    "regions": "region",
    "province": "province",
    "provinces": "province",
    "municipality": "municipality",
    "municipalities": "municipality",
}


@dataclass(frozen=True)
class ReferenceRecord:
    """One canonical geographic record loaded from a metadata workbook."""

    identifier: str | None
    name: str
    parent_identifier: str | None
    normalized_name: str


@dataclass(frozen=True)
class MatchResult:
    """The result of matching one incoming cell against canonical records."""

    record: ReferenceRecord | None
    status: str
    score: float
    suggestion: str = ""


@dataclass(frozen=True)
class GeographicCleanResult:
    """Paths and counts generated by a cleanup run."""

    output_file: Path
    report_file: Path
    sheets_processed: int
    rows_processed: int
    cells_changed: int
    review_count: int


class ReferenceIndex:
    """Canonical records and their hierarchy relationships."""

    def __init__(self, records: dict[str, list[ReferenceRecord]]):
        self.records = records

    def candidates(
        self,
        level: str,
        parent: ReferenceRecord | None = None,
    ) -> list[ReferenceRecord]:
        all_records = self.records[level]
        if parent is None or parent.identifier is None:
            return all_records

        related = [
            record
            for record in all_records
            if record.parent_identifier == parent.identifier
        ]
        # Metadata containing names only can still be used, with ambiguity
        # protection. If relationships are present, never escape the matched
        # parent merely because that parent's child list is incomplete.
        has_relationships = any(
            record.parent_identifier is not None for record in all_records
        )
        return related if has_relationships else all_records


def _repair_mojibake(value: str) -> str:
    """Repair common UTF-8-as-Latin-1 damage without altering valid Unicode."""
    if not any(marker in value for marker in ("Ã", "Â", "â")):
        return value
    try:
        return value.encode("latin-1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return value


def normalize_location_name(value: object) -> str:
    """Create a comparison-only form of a geographic name."""
    if value is None or pd.isna(value):
        return ""

    text = _repair_mojibake(str(value)).strip().casefold()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(char for char in text if not unicodedata.combining(char))
    text = text.replace("&", " and ")
    text = re.sub(r"[^a-z0-9]+", " ", text)
    tokens = text.split()

    replacements = {
        "sta": "santa",
        "sto": "santo",
        "st": "saint",
    }
    tokens = [replacements.get(token, token) for token in tokens]

    # These are presentation prefixes rather than distinguishing name parts.
    if tokens[:2] in (["city", "of"], ["province", "of"]):
        tokens = tokens[2:]
    elif tokens[:2] == ["municipality", "of"]:
        tokens = tokens[2:]

    return " ".join(tokens)


def _normalize_column_name(value: object) -> str:
    if value is None:
        return ""
    return re.sub(r"[^a-z0-9]+", "", str(value).strip().casefold())


def _normalize_identifier(value: object) -> str | None:
    if value is None or pd.isna(value):
        return None
    text = str(value).strip()
    if not text:
        return None
    if re.fullmatch(r"\d+\.0", text):
        text = text[:-2]
    return text


def _find_reference_file(metadata_dir: Path, expected_stem: str) -> Path:
    matches = sorted(
        path
        for path in metadata_dir.iterdir()
        if path.is_file()
        and path.suffix.casefold() == ".xlsx"
        and path.stem.casefold() == expected_stem.casefold()
    )
    if not matches:
        raise FileNotFoundError(
            f"Missing metadata workbook: {expected_stem}.xlsx "
            f"(expected in {metadata_dir})"
        )
    if len(matches) > 1:
        names = ", ".join(path.name for path in matches)
        raise ValueError(
            f"More than one metadata workbook matches '{expected_stem}': {names}"
        )
    return matches[0]


def _load_reference_records(path: Path, level: str) -> list[ReferenceRecord]:
    dataframe = pd.read_excel(path, dtype=object, engine="openpyxl")
    columns = {_normalize_column_name(column): column for column in dataframe.columns}

    if "name" not in columns:
        raise ValueError(f"{path.name} must contain a column named 'name'.")

    name_column = columns["name"]
    id_column = columns.get("id")
    expected_parent = PARENT_COLUMNS[level]
    parent_column = (
        columns.get(_normalize_column_name(expected_parent)) if expected_parent else None
    )

    records: list[ReferenceRecord] = []
    for _, row in dataframe.iterrows():
        raw_name = row[name_column]
        normalized = normalize_location_name(raw_name)
        if not normalized:
            continue

        records.append(
            ReferenceRecord(
                identifier=_normalize_identifier(row[id_column]) if id_column else None,
                name=_repair_mojibake(str(raw_name)).strip(),
                parent_identifier=(
                    _normalize_identifier(row[parent_column]) if parent_column else None
                ),
                normalized_name=normalized,
            )
        )

    if not records:
        raise ValueError(f"{path.name} has no usable values in its 'name' column.")
    return records


def load_reference_index(metadata_dir: str | Path) -> ReferenceIndex:
    """Load the three required canonical metadata workbooks."""
    directory = Path(metadata_dir)
    if not directory.is_dir():
        raise NotADirectoryError(f"Metadata folder not found: {directory}")

    records: dict[str, list[ReferenceRecord]] = {}
    for level, expected_stem in REFERENCE_FILENAMES.items():
        reference_file = _find_reference_file(directory, expected_stem)
        records[level] = _load_reference_records(reference_file, level)
    return ReferenceIndex(records)


def _match_location(
    value: object,
    candidates: Iterable[ReferenceRecord],
    threshold: float,
    minimum_gap: float,
) -> MatchResult:
    incoming = normalize_location_name(value)
    if not incoming:
        return MatchResult(None, "blank", 0.0)

    by_normalized: dict[str, list[ReferenceRecord]] = defaultdict(list)
    for candidate in candidates:
        by_normalized[candidate.normalized_name].append(candidate)

    exact = by_normalized.get(incoming, [])
    if len(exact) == 1:
        return MatchResult(exact[0], "exact", 100.0, exact[0].name)
    if len(exact) > 1:
        return MatchResult(None, "ambiguous", 100.0, exact[0].name)
    if not by_normalized:
        return MatchResult(None, "unmatched", 0.0)

    scored = process.extract(
        incoming,
        list(by_normalized),
        scorer=fuzz.WRatio,
        limit=2,
    )
    best_name, best_score, _ = scored[0]
    best_records = by_normalized[best_name]
    second_score = scored[1][1] if len(scored) > 1 else 0.0
    suggestion = best_records[0].name

    if len(best_records) > 1:
        return MatchResult(None, "ambiguous", float(best_score), suggestion)
    if best_score >= threshold and best_score - second_score >= minimum_gap:
        return MatchResult(best_records[0], "fuzzy", float(best_score), suggestion)
    if best_score >= threshold:
        return MatchResult(None, "ambiguous", float(best_score), suggestion)
    return MatchResult(None, "unmatched", float(best_score), suggestion)


def _detect_headers(worksheet, scan_rows: int = 20) -> tuple[int, dict[str, int]] | None:
    best: tuple[int, dict[str, int], set[str]] | None = None
    best_count = 0
    last_row = min(worksheet.max_row, scan_rows)

    for row_number in range(1, last_row + 1):
        detected: dict[str, int] = {}
        duplicates: set[str] = set()
        for column_number in range(1, worksheet.max_column + 1):
            header = _normalize_column_name(
                worksheet.cell(row=row_number, column=column_number).value
            )
            level = HEADER_ALIASES.get(header)
            if level is None:
                continue
            if level in detected:
                duplicates.add(level)
            else:
                detected[level] = column_number

        if len(detected) > best_count:
            best = (row_number, detected, duplicates)
            best_count = len(detected)

    if best is None:
        return None
    row_number, detected, duplicates = best
    if duplicates:
        duplicate_list = ", ".join(sorted(duplicates))
        raise ValueError(
            f"Worksheet '{worksheet.title}' has duplicate geographic columns "
            f"on row {row_number}: {duplicate_list}."
        )
    return row_number, detected


def _unique_output_path(destination: Path, filename: str) -> Path:
    candidate = destination / filename
    if not candidate.exists():
        return candidate

    stem = Path(filename).stem
    suffix = Path(filename).suffix
    counter = 2
    while True:
        candidate = destination / f"{stem}_{counter}{suffix}"
        if not candidate.exists():
            return candidate
        counter += 1


def _safe_report_value(value: object) -> object:
    """Prevent source text from becoming a formula in the generated report."""
    if isinstance(value, str) and value.startswith(("=", "+", "-", "@")):
        return "'" + value
    return value


def _write_report(report_file: Path, entries: list[dict[str, object]]) -> None:
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = "Geographic Match Report"
    headers = [
        "worksheet",
        "excel_row",
        "field",
        "original_value",
        "replacement_or_suggestion",
        "status",
        "score",
    ]
    worksheet.append(headers)

    header_fill = PatternFill("solid", fgColor="1F4E78")
    for cell in worksheet[1]:
        cell.font = Font(color="FFFFFF", bold=True)
        cell.fill = header_fill

    for entry in entries:
        worksheet.append([_safe_report_value(entry[header]) for header in headers])

    worksheet.freeze_panes = "A2"
    worksheet.auto_filter.ref = worksheet.dimensions
    widths = [24, 12, 16, 32, 36, 14, 10]
    for index, width in enumerate(widths, start=1):
        worksheet.column_dimensions[get_column_letter(index)].width = width
    workbook.save(report_file)


def clean_geographic_names(
    input_file: str | Path,
    metadata_dir: str | Path,
    output_dir: str | Path,
    threshold: float = 90.0,
    minimum_gap: float = 5.0,
    progress_callback: ProgressCallback | None = None,
) -> GeographicCleanResult:
    """Correct geographic columns in a copy of an Excel workbook.

    Headers are detected in the first 20 rows of every worksheet. Accepted
    headers are the singular and plural forms of region, province, and
    municipality. Low-confidence or ambiguous values remain unchanged.
    """
    input_path = Path(input_file)
    destination = Path(output_dir)
    if not input_path.is_file():
        raise FileNotFoundError(f"Input file not found: {input_path}")
    if input_path.suffix.casefold() != ".xlsx":
        raise ValueError(
            "The geographic cleaner supports only .xlsx files; "
            "macro-enabled files are blocked."
        )
    if not 0 <= threshold <= 100:
        raise ValueError("Match threshold must be between 0 and 100.")
    if minimum_gap < 0:
        raise ValueError("Minimum score gap cannot be negative.")

    references = load_reference_index(metadata_dir)
    workbook = load_workbook(input_path, keep_links=False)

    detected_sheets: list[tuple[object, int, dict[str, int]]] = []
    for worksheet in workbook.worksheets:
        detected = _detect_headers(worksheet)
        if detected is not None:
            header_row, columns = detected
            detected_sheets.append((worksheet, header_row, columns))

    if not detected_sheets:
        accepted = "region(s), province(s), or municipality/municipalities"
        raise ValueError(
            f"No geographic columns were found. Expected headers such as {accepted} "
            "within the first 20 rows of a worksheet."
        )

    total_rows = sum(
        max(0, worksheet.max_row - header_row)
        for worksheet, header_row, _ in detected_sheets
    )
    processed_rows = 0
    cells_changed = 0
    review_count = 0
    report_entries: list[dict[str, object]] = []
    level_order = ("region", "province", "municipality")

    for worksheet, header_row, columns in detected_sheets:
        for row_number in range(header_row + 1, worksheet.max_row + 1):
            matched_parents: dict[str, ReferenceRecord | None] = {
                "region": None,
                "province": None,
            }
            for level in level_order:
                column_number = columns.get(level)
                if column_number is None:
                    continue

                cell = worksheet.cell(row=row_number, column=column_number)
                if cell.value is None or not str(cell.value).strip():
                    continue

                parent = None
                if level == "province":
                    parent = matched_parents["region"]
                elif level == "municipality":
                    parent = matched_parents["province"]

                candidates = references.candidates(level, parent)
                result = _match_location(
                    cell.value,
                    candidates,
                    threshold=threshold,
                    minimum_gap=minimum_gap,
                )

                if result.record is not None:
                    if level in matched_parents:
                        matched_parents[level] = result.record
                    original_value = cell.value
                    if str(original_value) != result.record.name:
                        cell.value = result.record.name
                        cells_changed += 1
                        report_entries.append(
                            {
                                "worksheet": worksheet.title,
                                "excel_row": row_number,
                                "field": level,
                                "original_value": original_value,
                                "replacement_or_suggestion": result.record.name,
                                "status": result.status,
                                "score": round(result.score, 2),
                            }
                        )
                elif result.status in {"ambiguous", "unmatched"}:
                    review_count += 1
                    report_entries.append(
                        {
                            "worksheet": worksheet.title,
                            "excel_row": row_number,
                            "field": level,
                            "original_value": cell.value,
                            "replacement_or_suggestion": result.suggestion,
                            "status": result.status,
                            "score": round(result.score, 2),
                        }
                    )

            processed_rows += 1
            if progress_callback is not None and (
                processed_rows == total_rows or processed_rows % 100 == 0
            ):
                progress_callback(
                    processed_rows,
                    max(total_rows, 1),
                    f"Processing {worksheet.title}: row {row_number}",
                )

    destination.mkdir(parents=True, exist_ok=True)
    output_file = _unique_output_path(
        destination,
        f"{input_path.stem}_geography_fixed{input_path.suffix}",
    )
    report_file = _unique_output_path(
        destination,
        f"{input_path.stem}_geography_report.xlsx",
    )
    workbook.save(output_file)
    _write_report(report_file, report_entries)

    return GeographicCleanResult(
        output_file=output_file,
        report_file=report_file,
        sheets_processed=len(detected_sheets),
        rows_processed=processed_rows,
        cells_changed=cells_changed,
        review_count=review_count,
    )
